[Begginer idea] CSSGram
laisfrigerio/app-ideas pull request #7
Opened 2022-10-06 20:55 UTC by AlexMayol

As stated on the added file, the goal is to create a tool to add various filters to an uploaded image.

2022-10-08 21:14 UTC, laisfrigerio approved these changes

2022-10-08 21:17 UTC, laisfrigerio requested changes

2022-10-08 21:17 UTC, laisfrigerio commented on Projects/1-Beginner/CSSGram.md
> +# Product Landing Page
Hey @AlexMayol  
Please, edit the name of exercise.

2022-10-08 21:17 UTC, laisfrigerio commented on Projects/1-Beginner/CSSGram.md
> +# Product Landing Page
And add this exercise reference on the main README

2022-10-09 16:42 UTC, AlexMayol commented
@laisfrigerio Nice catch, sorry! It's edited now 😄

2022-10-11 20:58 UTC, laisfrigerio commented
Great job, @AlexMayol 

Thanks for your contribution!!!

2022-10-11 20:58 UTC, merged